### ISSUE TITLE
Adding new users to registry?

### ISSUE THREAD

**Issue by mdom** [reednj/twtxt-directory#3]
Hi, would it be possible to add new users to, uhm, one of the registries?

**Comment by reednj** [comment]
You mean just a single user, or in bulk somehow? Because you can add single users just by putting in the name and url on http://twtxt.reednj.com/

**Comment by reednj** [comment]
Or you can do it through an api with a POST to `/user/add` with the fields `username` and `url` set

**Comment by mdom** [comment]
Oh, sorry, i haven't described it very well. As http://twtxt.reednj.com/ is probably the most popular aggregator of twtxt files, i currently scrape it to find new users. It would be perfect if one could export the data somehow. Or if i could dream, the directory would implement at least the user part of the registry specification so other registries could import the data?

**Comment by reednj** [comment]
Ohh, right gotcha. I just added http://twtxt.reednj.com/users.txt for this. Eventually I will add the registry standard as well, but for now this should give you what you want.

**Comment by mdom** [comment]
Thanks!
