### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by VonKavalier** [reednj/twtxt-directory#5]
I created an account, linking github, for testing, and now this useless account is showed up in the list, how can I remove it ?

**Comment by reednj** [comment]
There is no way to do this at the moment, but if you send me the username I will delete it

**Comment by VonKavalier** [comment]
Oh ok :) 

Well it's `VonKavalier`, here's the link of the profile : http://twtxt.xyz/user/8660ef3f25f330be

Thank you ! And congrats on that project of yours, I made an article (in French) about twtxt and talked about your web client, in case it could help people dive in ^^

**Comment by reednj** [comment]
Done.

thanks for the article :)
