### ISSUE TITLE
error: certificate verify failed (with Let's Encrypt ECC certificate)

### ISSUE THREAD

**Issue by rnkn** [reednj/twtxt-directory#9]
Hello,

Sorry I see this project isn't very active anymore, but I'm trying to add a user (me!) and getting:
```
$ curl -X POST -F 'username=pwr' -F 'url=https://skeletons.cc/twtxt.txt' http://twtxt.xyz/user/add
could not load updates from that url (SSL_connect returned=1 errno=0 state=error: certificate verify failed)
```
with the same via the website.

I'm not sure why the certificate would fail to verify, unless there's a problem with using ECC certificates?

Thanks.

**Comment by rh3xp** [comment]
I just found this amazing project and added myself on the website, and it was successful without logging it.
Do check out if my username is visible to you. its `thenerdsuperuser`.

**Comment by rnkn** [comment]
Pretty sure this was my misconfigured certificate.
